version: '3'

services:
  frontend:
    container_name: docker-frontend
    image: node:17.6.0
    working_dir: /home/node/app
    command: "sh -c 'npm install && npm run build && npm run start'"
    user: "node"
    volumes:
      - ./frontend:/home/node/app
    networks:
      - docker-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        docker_id: ${DOCKER_UID}
        docker_user: ${DOCKER_USER}
    container_name: docker-api
    user: ${DOCKER_USER}
    volumes:
      - ./api:/usr/src/app
      - ${GOPATH}/pkg:/go/pkg
    command: air -c .air.toml && migrate && seeder
    links:
      - db
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - docker-network

  db:
    image: postgres:14.1-alpine
    container_name: docker-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - docker-network

  nginx:
    image: nginx:stable-alpine
    container_name: docker-nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
      - api_db
    networks:
      - docker-network


volumes:
  postgres_db:

networks:
  docker-network:
    driver: bridge
